version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: coolpack
    binary: coolpack
    main: ./main.go
    ldflags:
      - -s -w
      - -X github.com/coollabsio/coolpack/pkg/version.Version={{.Version}}
      - -X github.com/coollabsio/coolpack/pkg/version.Commit={{.Commit}}
      - -X github.com/coollabsio/coolpack/pkg/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: coolpack
    builds:
      - coolpack
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
